FROM python:latest

RUN apt update && apt install apt-file -y && apt-file update

RUN apt-get install build-essential
RUN python -m pip install --upgrade pip

WORKDIR /app

COPY ./requirements.txt ./requirements.txt

RUN python -m pip install -r requirements.txt

EXPOSE 8000

COPY . .

CMD ["uwsgi", "--ini", "/app/uwsgi.ini"]